{
 "title": "AWS Lambda Insights",
 "description": "AWS Lambda telemetry",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "period",
    "label": "Period",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "function_name",
    "label": "FunctionName",
    "query": {}
   },
   {
    "name": "lambda_log_groups",
    "label": "Log groups",
    "query": {}
   },
   { "name": "log_filter" }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors ($period)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "${function_name}", "Resource": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.Resource')} ${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Shutdown reason",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "${function_name}" },
     "expression": "fields @timestamp, function_name, shutdown_reason, @message\n| filter function_name = \"$function_name\"\n| sort @timestamp desc\n| filter ispresent(shutdown_reason)\n| display  @timestamp, shutdown_reason, @message",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "logGroups": [
      { "arn": "$lambda_log_groups", "name": "$lambda_log_groups" }
     ],
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "${function_name}" },
     "expression": "fields @timestamp, @message, @logStream, @log\n| sort @timestamp desc\n| filter  @log LIKE \"$function_name\"\n| filter @message =~ /WARN|ERROR/\n| display @timestamp, @message",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "logGroups": [
      { "arn": "$lambda_log_groups", "name": "$lambda_log_groups" }
     ],
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Concurrent Executions ($period)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$function_name", "Resource": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.Resource')}  ${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "Global ${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "UnreservedConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Throttles ($period)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "${function_name}", "Resource": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.Resource')}  ${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Duration ($period)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$function_name", "Resource": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.Resource')}  ${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$function_name", "Resource": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.Resource')}  ${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$function_name", "Resource": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('Dim.Resource')}  ${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "region": "$region",
     "statistic": "Minimum"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Network: p99 ($period)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "function_name": "${function_name}" },
     "metricName": "tx_bytes",
     "namespace": "LambdaInsights",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p99"
    },
    {
     "dimensions": { "function_name": "${function_name}" },
     "metricName": "rx_bytes",
     "namespace": "LambdaInsights",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p99"
    }
   ]
  },
  {
   "title": "Invocations sum ($period)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "${function_name}", "Resource": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cpu / Init time ($period)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "function_name": "${function_name}" },
     "metricName": "cpu_total_time",
     "namespace": "LambdaInsights",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p99"
    },
    {
     "dimensions": { "function_name": "${function_name}" },
     "metricName": "init_duration",
     "namespace": "LambdaInsights",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p99"
    }
   ]
  },
  {
   "title": "Memory ($period)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "dimensions": { "function_name": "${function_name}" },
     "metricName": "total_memory",
     "namespace": "LambdaInsights",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p99"
    },
    {
     "dimensions": { "function_name": "${function_name}" },
     "metricName": "memory_utilization",
     "namespace": "LambdaInsights",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Lambda",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "${function_name}" },
     "expression": "fields @timestamp, @message, @logStream, @log, function_name\n| filter  (@log LIKE \"$function_name\" OR function_name LIKE \"$function_name\")\n| filter @message LIKE \"${log_filter}\"\n| sort @timestamp desc\n| display @timestamp, @message ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "logGroups": [
      { "arn": "$lambda_log_groups", "name": "$lambda_log_groups" }
     ],
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Insights",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "${function_name}" },
     "expression": "fields @timestamp, function_name, @message\n| filter function_name = \"$function_name\"\n| sort @timestamp desc\n| display @timestamp, @message",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "logGroups": [
      { "arn": "$lambda_log_groups", "name": "$lambda_log_groups" }
     ],
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "${period}",
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}