{
 "title": "AWS DynamoDB CloudWatch",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "table",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "UserErrors",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Usage (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Class": "None", "Resource": "*", "Service": "DynamoDB", "Type": "Resource" },
     "metricName": "ResourceCount",
     "namespace": "AWS/Usage",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Reads (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "AccountMaxReads",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "AccountMaxTableLevelReads",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "AccountProvisionedReadCapacityUtilization",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "MaxProvisionedTableReadCapacityUtilization",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Writes (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "AccountMaxWrites",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "AccountMaxTableLevelWrites",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "AccountProvisionedWriteCapacityUtilization",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "metricName": "MaxProvisionedTableWriteCapacityUtilization",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Errors (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throttling (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "*"
     },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "*"
     },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "*"
     },
     "metricName": "OnlineIndexThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Successful Requests Count (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Successful Requests Durations (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Reads (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ConditionalCheckFailedRequests",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "OnDemandMaxReadRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "Operation": "*", "TableName": "*" },
     "metricName": "ReturnedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Writes (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "OnDemandMaxWriteRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "ProvisionedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "TimeToLiveDeletedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "*" },
     "metricName": "TransactionConflict",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Table: ${table}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }, "repeat": "table" },
  {
   "title": "Errors (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throttling (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnlineIndexThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Successful Requests Count (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Successful Requests Durations (${period})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Reads (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ConditionalCheckFailedRequests",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "OnDemandMaxReadRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "Operation": "*", "TableName": "${table}" },
     "metricName": "ReturnedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Writes (${period})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "OnDemandMaxWriteRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "ProvisionedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "TimeToLiveDeletedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "${table}" },
     "metricName": "TransactionConflict",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Global Secondary Index: ${table}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 476 },
   "repeat": "table"
  },
  {
   "title": "Global Secondary Indexes Reads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 477 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnDemandMaxReadRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Global Secondary Indexes Writes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 477 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnDemandMaxWriteRequestUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnlineIndexConsumedWriteCapacity",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "OnlineIndexPercentageProgress",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "GlobalSecondaryIndexName": "*",
      "TableName": "${table}"
     },
     "metricName": "PendingReplicationCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "DynamoDB Streams: ${table}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 632 }, "repeat": "table" },
  {
   "title": "DynamoDB Stream",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 633 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "StreamLabel": "*", "TableName": "${table}" },
     "metricName": "ReturnedBytes",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "Operation": "*", "StreamLabel": "*", "TableName": "${table}" },
     "metricName": "ReturnedRecordsCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "DynamoDB Stream Durations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 633 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Operation": "*", "StreamLabel": "*", "TableName": "${table}" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Kinesis Data Streams: ${table}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 788 }, "repeat": "table" },
  {
   "title": "Kinesis Data Stream",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 789 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DelegatedOperation": "*", "TableName": "${table}" },
     "metricName": "AgeOfOldestUnreplicatedRecord",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DelegatedOperation": "*", "TableName": "${table}" },
     "metricName": "ConsumedChangeDataCaptureUnits",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DelegatedOperation": "*", "TableName": "${table}" },
     "metricName": "FailedToReplicateRecordCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DelegatedOperation": "*", "TableName": "${table}" },
     "metricName": "ThrottledPutRecordCount",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Global Table: ${table}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 944 }, "repeat": "table" },
  {
   "title": "Global Table",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 945 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ReceivingRegion": "*", "TableName": "${table}" },
     "metricName": "ReplicationLatency",
     "namespace": "AWS/DynamoDB",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}