{
 "title": "GrafanaCloud Monitoring / Billing / Usage",
 "tags": [
  "billing",
  "grafanacloud"
 ],
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_slug",
    "label": "Org",
    "query": {
     "query": "label_values(grafanacloud_org_info,org_slug)"
    }
   },
   {
    "name": "org_id",
    "label": "Org ID",
    "query": {
     "query": "label_values(grafanacloud_org_info{org_slug=\"$org_slug\"},org_id)"
    }
   },
   { "name": "tenant", "label": "Tenant", "query": "main : .*" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "description": "Negative Delta: usage > commit per month",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafanacloud_org_total_overage{org_id=\"${org_id}\"})",
     "legendFormat": "Usage per month"
    },
    {
     "expr": "scalar(grafanacloud_org_spend_commit_balance_total{org_id=\"${org_id}\"})\r\n/\r\n(\r\n    (year(grafanacloud_org_contract_end_date{org_id=\"${org_id}\"}) - scalar(year(vector(time())))) * 12 \r\n    + \r\n    (month(grafanacloud_org_contract_end_date{org_id=\"${org_id}\"}) - scalar(month(vector(time()))))\r\n    + 1\r\n)\r\n",
     "legendFormat": "Committed per month"
    },
    {
     "expr": "(\r\n    scalar(grafanacloud_org_spend_commit_balance_total{org_id=\"${org_id}\"})\r\n    /\r\n    (\r\n        (year(grafanacloud_org_contract_end_date{org_id=\"${org_id}\"}) - scalar(year(vector(time())))) * 12 \r\n        + \r\n        (month(grafanacloud_org_contract_end_date{org_id=\"${org_id}\"}) - scalar(month(vector(time()))))\r\n        + 1\r\n    )\r\n)\r\n- \r\nscalar(grafanacloud_org_total_overage{org_id=\"${org_id}\"})",
     "legendFormat": "Balance"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "type": "annolist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 } },
  { "title": "🔥Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "🔥GrafanaCloud Firing alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 } },
  { "title": "All GrafanaCloud alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 } },
  { "title": "💸Billing (${tenant:text})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "tenant" },
  {
   "title": "Highest Metrics DPM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(\n  max by(id, name) (\n    60 * grafanacloud_instance_samples_per_second{org_id=\"${org_id}\"}\n    / grafanacloud_instance_active_series{org_id=\"${org_id}\"}\n\n    * on(id) group_left(name) grafanacloud_instance_info{org_id=\"${org_id}\", name=~\"${tenant:value}\"}\n  )\n)\n"
    },
    {
     "expr": "scalar(grafanacloud_org_metrics_included_dpm_per_series{org_id=\"$org_id\"})"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max(grafanacloud_instance_billable_usage{org_id=\"${org_id}\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_metrics_billable_series{org_id=\"${org_id}\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_metrics_overage{org_id=\"${org_id}\"}) * on (id) group_left(name) max by(id, name) (grafanacloud_instance_info{name=~\"${tenant:value}\", org_id=\"${org_id}\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max(grafanacloud_traces_instance_usage{org_id=\"${org_id}\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_traces_usage{org_id=\"${org_id}\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_traces_overage{org_id=\"${org_id}\"}) * on (id) group_left(name) max by(id, name) (grafanacloud_traces_instance_info{name=~\"${tenant:value}\", org_id=\"${org_id}\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max(grafanacloud_logs_instance_usage{org_id=\"${org_id}\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage{org_id=\"${org_id}\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_logs_overage{org_id=\"${org_id}\"}) * on (id) group_left(name) max by(id, name) (grafanacloud_logs_instance_info{name=~\"${tenant:value}\", org_id=\"${org_id}\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(grafanacloud_grafana_instance_active_user_count{org_id=\"${org_id}\"}) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info{name=~\"${tenant:value}\", org_id=\"${org_id}\"}) by (name)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum(sum(sum(grafanacloud_grafana_instance_active_user_count{org_id=\"${org_id}\"}) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info{name=~\"${tenant:value}\", org_id=\"${org_id}\"}) by (name))\r\n/\r\nsum(sum(sum(grafanacloud_grafana_instance_active_user_count{org_id=\"${org_id}\"}) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info{org_id=\"${org_id}\"}) by (name))\r\n*\r\nsum(avg without(monetary) (grafanacloud_org_grafana_overage{org_id=\"${org_id}\"}))",
     "legendFormat": "Billable Users"
    }
   ]
  },
  { "title": "💸Billable Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Billable Overall Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_org_total_overage{org_id=\"${org_id}\"})",
     "legendFormat": "Usage per month"
    },
    {
     "expr": "scalar(grafanacloud_org_spend_commit_balance_total{org_id=\"${org_id}\"})\r\n/\r\n(\r\n    (year(grafanacloud_org_contract_end_date{org_id=\"${org_id}\"}) - scalar(year(vector(time())))) * 12 \r\n    + \r\n    (month(grafanacloud_org_contract_end_date{org_id=\"${org_id}\"}) - scalar(month(vector(time()))))\r\n    + 1\r\n)\r\n",
     "legendFormat": "Committed per month"
    },
    {
     "expression": "$CommittedPerMonth - $TotalPerMonth",
     "type": "math"
    },
    {
     "expr": "grafanacloud_org_spend_commit_credit_total{org_id=\"${org_id}\"}",
     "legendFormat": "Initial Commit"
    }
   ]
  },
  { "title": "💥Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Discarded Metric Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "targets": [
    {
     "expr": "sum(max(grafanacloud_instance_samples_discarded_per_second{org_id=\"${org_id}\"}) by (id, reason)) by (id, reason) * on(id) group_left(name) grafanacloud_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics Active Series Ingestion Rate per Minute (DPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(grafanacloud_instance_samples_per_second{org_id=\"${org_id}\"} * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Log Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_samples_discarded_per_second{org_id=\"${org_id}\"}) by (id, reason) * on(id) group_left(name) grafanacloud_logs_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second{org_id=\"${org_id}\"}) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Fair Usage Quota",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "(sort_desc(\r\n  sum_over_time(\r\n    sum by (id) (\r\n      grafanacloud_logs_instance_query_bytes:rate5m{org_id=\"${org_id}\"}\r\n    ) [$__range:1m]\r\n  ) > 0) /\r\n  (sum_over_time(\r\n    sum by (id) (\r\n      grafanacloud_logs_instance_billable_bytes_received_per_second{org_id=\"${org_id}\"}\r\n    ) [$__range:1m]\r\n  ) > 0)\r\n) * on(id) group_left(name) grafanacloud_logs_instance_info{org_id=\"${org_id}\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Spans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_discarded_spans_total:rate5m{org_id=\"${org_id}\"}) by (id, reason) * on(id) group_left(name) grafanacloud_traces_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "❌Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Dashboards",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "topk(20, sum by (dashboardName, folderName) (\n    count_over_time({instance_type=\"grafana\", org_id=\"${org_id}\"} \n        |= \"data-request\" |~ `error=\".+\"` != \"dashboardId=0\"\n        | regexp `folderName=(?P<folderName>.+) dashboardName=(?P<dashboardName>.+) dashboardId=`\n        | label_format dashboardName=`{{replace \"\\\"\" \"\" .dashboardName}}`\n        | label_format folderName=`{{replace \"\\\"\" \"\" .folderName}}`\n[$__range])))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "📈Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Top dashboard",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "count by(folderName, dashboardName, instance_id) (rate({instance_type=\"grafana\", org_id=\"$org_id\"} | logfmt [$__auto]))",
     "legendFormat": "{{instance_id}} / {{folderName}} / {{dashboardName}}"
    }
   ]
  },
  { "title": "Billable Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Current Billable Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users{org_id=\"${org_id}\"}",
     "legendFormat": "Total Unique Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_grafana{org_id=\"${org_id}\"}",
     "legendFormat": "Grafana Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_oncall{org_id=\"${org_id}\"}",
     "legendFormat": "OnCall Users"
    }
   ]
  },
  {
   "title": "Total Billable Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users{org_id=\"${org_id}\"}",
     "legendFormat": "Billable Users"
    },
    {
     "expr": "grafanacloud_org_grafana_overage{org_id=\"${org_id}\"}",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_grafana_included_users{org_id=\"${org_id}\"}",
     "legendFormat": "Included Users"
    }
   ]
  },
  {
   "title": "Billable Users Breakdown",
   "type": "timeseries",
   "description": "Total Billable Users represents the number of unique Grafana and OnCall users across all instances. A user that is active in both Grafana and OnCall will be counted in each service separately, but will only be counted once in Total Billable Users. See [Billing for Active Users](https://grafana.com/docs/grafana-cloud/fundamentals/billing-and-usage/#billing-for-active-users) for additional information.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_billable_users_grafana{org_id=\"${org_id}\"}",
     "legendFormat": "Grafana Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_oncall{org_id=\"${org_id}\"}",
     "legendFormat": "OnCall users"
    }
   ]
  },
  {
   "title": "Current Additional Users Amount",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_overage{org_id=\"${org_id}\"}",
     "legendFormat": "{{cluster}} / {{org_id}}"
    }
   ]
  },
  { "title": "Billable Usage per Signal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Total Billable Logs Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "delta(grafanacloud_org_logs_usage{org_id=\"${org_id}\"}[24h])",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "delta(grafanacloud_org_logs_overage{org_id=\"${org_id}\"}[24h])",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "delta(grafanacloud_org_logs_included_usage{org_id=\"${org_id}\"}[24h])",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_logs_instance_usage{org_id=\"${org_id}\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage{org_id=\"${org_id}\"}) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage{org_id=\"${org_id}\"} * on (id) group_left(name) grafanacloud_logs_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  {
   "title": "Total Billable Metrics Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series{org_id=\"${org_id}\"}",
     "legendFormat": "Billable Series"
    },
    {
     "expr": "grafanacloud_org_metrics_overage{org_id=\"${org_id}\"}",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_metrics_included_series{org_id=\"${org_id}\"}",
     "legendFormat": "Included Series"
    },
    {
     "expr": "grafanacloud_org_graphite_metrics_billable_series{org_id=\"${org_id}\"}",
     "legendFormat": "Billable Graphite Series"
    },
    {
     "expr": "grafanacloud_org_graphite_metrics_overage{org_id=\"${org_id}\"}",
     "legendFormat": "Additional Graphite Usage Amount"
    },
    {
     "expr": "grafanacloud_org_graphite_metrics_included_series{org_id=\"${org_id}\"}",
     "legendFormat": "Included Graphite Series"
    },
    {
     "expr": "max(grafanacloud_instance_billable_usage{org_id=\"${org_id}\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_metrics_billable_series{org_id=\"${org_id}\"}) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_metrics_overage{org_id=\"${org_id}\"} * on (id) group_left(name) grafanacloud_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  {
   "title": "Total Billable Traces Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_traces_usage{org_id=\"${org_id}\"}",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "grafanacloud_org_traces_overage{org_id=\"${org_id}\"}",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_traces_included_usage{org_id=\"${org_id}\"}",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_traces_instance_usage{org_id=\"${org_id}\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_traces_usage{org_id=\"${org_id}\"}) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_traces_overage{org_id=\"${org_id}\"} * on (id) group_left(name) grafanacloud_traces_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  { "title": "Logs Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Logs Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second{org_id=\"${org_id}\"}) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Logs Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_query_bytes:rate5m{org_id=\"${org_id}\"}) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Metrics Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Metrics Ingestion Rate (DPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(grafanacloud_instance_samples_per_second{org_id=\"${org_id}\"} * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Tracing Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Traces Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_bytes_received_per_second{org_id=\"${org_id}\"}) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info{org_id=\"${org_id}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Query Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Query Usage Ratio",
   "type": "bargauge",
   "description": "Shows the ratio of queried to ingested bytes over the selected time period on each of your stacks.",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 134 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\n  sum_over_time(\n    sum by (id) (\n      grafanacloud_logs_instance_query_bytes:rate5m{org_id=\"${org_id}\"}\n    ) [$__range:1m]\n  ) /\n  sum_over_time(\n    sum by (id) (\n      grafanacloud_logs_instance_billable_bytes_received_per_second{org_id=\"${org_id}\"}\n    ) [$__range:1m]\n  )\n) * on(id) group_left(name) grafanacloud_logs_instance_info{org_id=\"${org_id}\"}\n",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "grafanacloud_org_logs_included_query_to_ingest_ratio{org_id=\"${org_id}\"}"
    }
   ]
  },
  {
   "title": "Query Fair Use Ratio",
   "type": "stat",
   "description": "The query fair usage ratio configured for your current plan",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_logs_included_query_to_ingest_ratio{org_id=\"${org_id}\"}"
    }
   ]
  }
 ]
}