{
 "title": "GrafanaCloud Monitoring / Billing / Usage",
 "tags": [
  "billing",
  "grafanacloud"
 ],
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "label": "Tenant", "query": "main : .*" }
  ]
 },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "annolist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 } },
  { "title": "🔥Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "title": "🔥GrafanaCloud Firing alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 } },
  { "title": "All GrafanaCloud alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 } },
  { "title": "💸Billing (${tenant:text})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "tenant" },
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max(grafanacloud_instance_billable_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_metrics_billable_series) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_metrics_overage) * on (id) group_left(name) max by(id, name) (grafanacloud_instance_info{name=~\"${tenant:value}\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_logs_overage) * on (id) group_left(name) max by(id, name) (grafanacloud_logs_instance_info{name=~\"${tenant:value}\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "max(grafanacloud_traces_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_traces_usage) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_traces_overage) * on (id) group_left(name) max by(id, name) (grafanacloud_traces_instance_info{name=~\"${tenant:value}\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(grafanacloud_grafana_instance_active_user_count) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info{name=~\"${tenant:value}\"}) by (name)",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum(sum(sum(grafanacloud_grafana_instance_active_user_count) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info{name=~\"${tenant:value}\"}) by (name))\r\n/\r\nsum(sum(sum(grafanacloud_grafana_instance_active_user_count) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info) by (name))\r\n*\r\nsum(avg without(monetary) (grafanacloud_org_grafana_overage))",
     "legendFormat": "Billable Users"
    }
   ]
  },
  { "title": "💸Billable Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total Billable Overall Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "targets": [
    {
     "expr": "delta(grafanacloud_org_total_overage[24h])",
     "legendFormat": "Total additional usage"
    }
   ]
  },
  { "title": "💥Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Discarded Metric Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "targets": [
    {
     "expr": "sum(max(grafanacloud_instance_samples_discarded_per_second) by (id, reason)) by (id, reason) * on(id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics Active Series Ingestion Rate per Minute (DPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(grafanacloud_instance_samples_per_second{} * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Log Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_samples_discarded_per_second) by (id, reason) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second{}) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Fair Usage Quota",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "(sort_desc(\r\n  sum_over_time(\r\n    sum by (id) (\r\n      grafanacloud_logs_instance_query_bytes:rate5m\r\n    ) [$__range:1m]\r\n  ) > 0) /\r\n  (sum_over_time(\r\n    sum by (id) (\r\n      grafanacloud_logs_instance_billable_bytes_received_per_second\r\n    ) [$__range:1m]\r\n  ) > 0)\r\n) * on(id) group_left(name) grafanacloud_logs_instance_info\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Spans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "si:/s" } },
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_discarded_spans_total:rate5m) by (id, reason) * on(id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "❌Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Dashboards",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "topk(20, sum by (dashboardName, folderName) (\n    count_over_time({instance_type=\"grafana\"} \n        |= \"data-request\" |~ `error=\".+\"` != \"dashboardId=0\"\n        | regexp `folderName=(?P<folderName>.+) dashboardName=(?P<dashboardName>.+) dashboardId=`\n        | label_format dashboardName=`{{replace \"\\\"\" \"\" .dashboardName}}`\n        | label_format folderName=`{{replace \"\\\"\" \"\" .folderName}}`\n[$__range])))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "📈Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Top dashboard",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "count by(folderName, dashboardName) (rate({instance_type=\"grafana\"} | logfmt [$__auto]))",
     "legendFormat": "{{folderName}} / {{dashboardName}}"
    }
   ]
  },
  {
   "title": "Billable Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Billable Users",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_billable_users",
       "legendFormat": "Total Unique Users"
      },
      {
       "expr": "grafanacloud_org_billable_users_grafana",
       "legendFormat": "Grafana Users"
      },
      {
       "expr": "grafanacloud_org_billable_users_oncall",
       "legendFormat": "OnCall Users"
      }
     ]
    },
    {
     "title": "Total Billable Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_billable_users",
       "legendFormat": "Billable Users"
      },
      {
       "expr": "grafanacloud_org_grafana_overage",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "grafanacloud_org_grafana_included_users",
       "legendFormat": "Included Users"
      }
     ]
    },
    {
     "title": "Billable Users Breakdown",
     "type": "timeseries",
     "description": "Total Billable Users represents the number of unique Grafana and OnCall users across all instances. A user that is active in both Grafana and OnCall will be counted in each service separately, but will only be counted once in Total Billable Users. See [Billing for Active Users](https://grafana.com/docs/grafana-cloud/fundamentals/billing-and-usage/#billing-for-active-users) for additional information.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_billable_users_grafana",
       "legendFormat": "Grafana Users"
      },
      {
       "expr": "grafanacloud_org_billable_users_oncall",
       "legendFormat": "OnCall users"
      }
     ]
    },
    {
     "title": "Current Additional Users Amount",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "prefix:$" } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_overage",
       "legendFormat": "{{cluster}} / {{org_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Billable Usage per Signal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Billable Logs Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "delta(grafanacloud_org_logs_usage[24h])",
       "legendFormat": "Billable Usage"
      },
      {
       "expr": "delta(grafanacloud_org_logs_overage[24h])",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "delta(grafanacloud_org_logs_included_usage[24h])",
       "legendFormat": "Included Usage"
      },
      {
       "expr": "max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info",
       "legendFormat": "Additional Usage Amount - {{ name }}"
      }
     ]
    },
    {
     "title": "Total Billable Metrics Series",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_metrics_billable_series",
       "legendFormat": "Billable Series"
      },
      {
       "expr": "grafanacloud_org_metrics_overage",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "grafanacloud_org_metrics_included_series",
       "legendFormat": "Included Series"
      },
      {
       "expr": "grafanacloud_org_graphite_metrics_billable_series",
       "legendFormat": "Billable Graphite Series"
      },
      {
       "expr": "grafanacloud_org_graphite_metrics_overage",
       "legendFormat": "Additional Graphite Usage Amount"
      },
      {
       "expr": "grafanacloud_org_graphite_metrics_included_series",
       "legendFormat": "Included Graphite Series"
      },
      {
       "expr": "max(grafanacloud_instance_billable_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_metrics_billable_series) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_metrics_overage * on (id) group_left(name) grafanacloud_instance_info",
       "legendFormat": "Additional Usage Amount - {{ name }}"
      }
     ]
    },
    {
     "title": "Total Billable Traces Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      { "expr": "grafanacloud_org_traces_usage", "legendFormat": "Billable Usage" },
      {
       "expr": "grafanacloud_org_traces_overage",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "grafanacloud_org_traces_included_usage",
       "legendFormat": "Included Usage"
      },
      {
       "expr": "max(grafanacloud_traces_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_traces_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_traces_overage * on (id) group_left(name) grafanacloud_traces_instance_info",
       "legendFormat": "Additional Usage Amount - {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Logs Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_logs_instance_query_bytes:rate5m) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Ingestion Rate (DPM)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(grafanacloud_instance_samples_per_second * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tracing Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traces Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_traces_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Usage Ratio",
     "type": "bargauge",
     "description": "Shows the ratio of queried to ingested bytes over the selected time period on each of your stacks.",
     "gridPos": { "h": 6, "w": 19, "x": 0, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(\n  sum_over_time(\n    sum by (id) (\n      grafanacloud_logs_instance_query_bytes:rate5m\n    ) [$__range:1m]\n  ) /\n  sum_over_time(\n    sum by (id) (\n      grafanacloud_logs_instance_billable_bytes_received_per_second\n    ) [$__range:1m]\n  )\n) * on(id) group_left(name) grafanacloud_logs_instance_info\n",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "grafanacloud_org_logs_included_query_to_ingest_ratio"
      }
     ]
    },
    {
     "title": "Query Fair Use Ratio",
     "type": "stat",
     "description": "The query fair usage ratio configured for your current plan",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_logs_included_query_to_ingest_ratio"
      }
     ]
    }
   ]
  }
 ]
}