{
 "title": "AWS SQS CloudWatch",
 "description": "This dashboard uses aws sqs namespace cloudwatch metrics.\r\nMultiple queues (deadletter and main queue) can be monitored at once.",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "queue",
    "label": "Queue name",
    "query": {}
   },
   {
    "name": "period",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "$queue ($period)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "queue" },
  {
   "title": "Message count / in flight",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Sent / Received / Deleted / Empty / Delayed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "NumberOfEmptyReceives",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "ApproximateNumberOfMessagesDelayed",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "SentMessageSize",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Max message age",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "QueueName": "$queue" },
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}