{
 "title": "AWS S3 CloudWatch",
 "description": "This dashboard uses aws s3 namespace cloudwatch metrics.",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "query": {}
   },
   {
    "name": "period",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "relative_time", "label": "Relative Time", "query": "7d,14d,30d" }
  ]
 },
 "panels": [
  { "title": "Daily storage metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "dimensions": { "BucketName": "*", "StorageType": "AllStorageTypes" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Buckets Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "BucketName": "*", "StorageType": "*" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "period": "1d",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Requests metrics (${period})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Errors (${period})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "4xxErrors",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "5xxErrors",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Requests (${period})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "AllRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "DeleteRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "GetRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "HeadRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "ListRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "PostRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "PutRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "SelectRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "SelectRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latencies (${period})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "FirstByteLatency",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "TotalRequestLatency",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes (${period})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "SelectScannedBytes",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "SelectReturnedBytes",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "*", "FilterId": "*" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Replication metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pending Replications (${period})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DestinationBucket": "*", "RuleId": "*", "SourceBucket": "*" },
     "metricName": "OperationsPendingReplication",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Bytes Pending Replications (${period})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DestinationBucket": "*", "RuleId": "*", "SourceBucket": "*" },
     "metricName": "BytesPendingReplication",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Replication Latency (${period})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DestinationBucket": "*", "RuleId": "*", "SourceBucket": "*" },
     "metricName": "ReplicationLatency",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Object Lambda request metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Errors (${period})",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "4xxErrors",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "5xxErrors",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latencies (${period})",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "FirstByteLatency",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "TotalRequestLatency",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Requests (${period})",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "AllRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "GetRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "PostRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "PutRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "DeleteRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "HeadRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "ListRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "ProxiedRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "InvokedLambda",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "LambdaResponseRequests",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "LambdaResponse4xx",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "LambdaResponse5xx",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes (${period})",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "AccessPointName": "*", "DataSourceARN": "*" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}