{
 "title": "AWS Keyspaces/Cassandra",
 "description": "AWS Keyspaces/Cassandra metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "query": {}
   },
   {
    "name": "period",
    "label": "Period",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumed Read Capacity Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Consumed Write Capacity Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Max Provisioned Table Read Capacity Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metricName": "MaxProvisionedTableReadCapacityUtilization",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "metricName": "MaxProvisionedTableReadCapacityUtilization",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    },
    {
     "metricName": "MaxProvisionedTableReadCapacityUtilization",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Provisioned Table Write Capacity Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metricName": "MaxProvisionedTableWriteCapacityUtilization",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "metricName": "MaxProvisionedTableWriteCapacityUtilization",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    },
    {
     "metricName": "MaxProvisionedTableWriteCapacityUtilization",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read Throttle Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Write Throttle Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "System / User Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "metricName": "SystemErrors",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "metricName": "UserErrors",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Per Connection Request Rate Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "PerConnectionRequestRateExceeded",
     "namespace": "AWS/Cassandra",
     "period": "${period}",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}