{
 "title": "GrafanaCloud Monitoring / Audit Log",
 "tags": [
  "security",
  "audit"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "username" }
  ]
 },
 "panels": [
  {
   "title": "Audit Log volume",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({instance_type=\"grafana\"} [$__auto])"
    }
   ]
  },
  {
   "title": "Activity by User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count by(username) (rate({instance_type=\"grafana\"} | logfmt | username =~ `.*$username` [$__auto]))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Usage stats",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(datasourceType, instance_id, eventName, dashboardName, source, panelId, username, datasourceName) (sum_over_time({instance_type=\"grafana\"} | logfmt | username =~ `.*$username` | unwrap duration [$__auto]))",
     "legendFormat": "{{labels.username}}"
    }
   ]
  },
  {
   "title": "Audit log",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{instance_type=\"grafana\"} | logfmt | username =~ `.*$username` | line_format `[{{.duration}}ms]{{.username}} {{.eventName}} {{.datasourceName}}`",
     "legendFormat": "{{labels.username}}"
    }
   ]
  }
 ]
}